apiVersion: 1
datasources:
  - name: VictoriaMetrics
    type: prometheus
    uid: victoriametrics                  # Фиксированный UID для переносимости проекта
    url: http://victoriametrics:8428      # имя сервиса в сети compose
    access: proxy
    isDefault: true
    editable: true
